create table canvases (
	id INT,
	title VARCHAR(50),
	owner_id INT
);
insert into canvases (id, title, owner_id) values (1, 'Automation Specialist I', 14);
insert into canvases (id, title, owner_id) values (2, 'Developer II', 36);
insert into canvases (id, title, owner_id) values (3, 'General Manager', 48);
insert into canvases (id, title, owner_id) values (4, 'Technical Writer', 25);
insert into canvases (id, title, owner_id) values (5, 'Systems Administrator I', 20);
insert into canvases (id, title, owner_id) values (6, 'Product Engineer', 28);
insert into canvases (id, title, owner_id) values (7, 'Teacher', 83);
insert into canvases (id, title, owner_id) values (8, 'Registered Nurse', 3);
insert into canvases (id, title, owner_id) values (9, 'Graphic Designer', 25);
insert into canvases (id, title, owner_id) values (10, 'Legal Assistant', 82);
insert into canvases (id, title, owner_id) values (11, 'Geologist IV', 88);
insert into canvases (id, title, owner_id) values (12, 'General Manager', 77);
insert into canvases (id, title, owner_id) values (13, 'Sales Representative', 96);
insert into canvases (id, title, owner_id) values (14, 'Professor', 77);
insert into canvases (id, title, owner_id) values (15, 'Research Assistant I', 81);
insert into canvases (id, title, owner_id) values (16, 'Statistician IV', 98);
insert into canvases (id, title, owner_id) values (17, 'Senior Editor', 3);
insert into canvases (id, title, owner_id) values (18, 'Paralegal', 68);
insert into canvases (id, title, owner_id) values (19, 'Senior Quality Engineer', 13);
insert into canvases (id, title, owner_id) values (20, 'Food Chemist', 16);
insert into canvases (id, title, owner_id) values (21, 'Geological Engineer', 24);
insert into canvases (id, title, owner_id) values (22, 'Assistant Manager', 49);
insert into canvases (id, title, owner_id) values (23, 'Internal Auditor', 32);
insert into canvases (id, title, owner_id) values (24, 'Internal Auditor', 35);
insert into canvases (id, title, owner_id) values (25, 'Occupational Therapist', 41);
insert into canvases (id, title, owner_id) values (26, 'VP Sales', 100);
insert into canvases (id, title, owner_id) values (27, 'Media Manager I', 81);
insert into canvases (id, title, owner_id) values (28, 'Account Coordinator', 20);
insert into canvases (id, title, owner_id) values (29, 'Chief Design Engineer', 28);
insert into canvases (id, title, owner_id) values (30, 'Electrical Engineer', 96);
insert into canvases (id, title, owner_id) values (31, 'Programmer Analyst III', 61);
insert into canvases (id, title, owner_id) values (32, 'Biostatistician I', 64);
insert into canvases (id, title, owner_id) values (33, 'Technical Writer', 7);
insert into canvases (id, title, owner_id) values (34, 'Health Coach IV', 63);
insert into canvases (id, title, owner_id) values (35, 'Software Engineer II', 48);
insert into canvases (id, title, owner_id) values (36, 'Marketing Manager', 73);
insert into canvases (id, title, owner_id) values (37, 'Developer II', 74);
insert into canvases (id, title, owner_id) values (38, 'Project Manager', 8);
insert into canvases (id, title, owner_id) values (39, 'Nurse', 63);
insert into canvases (id, title, owner_id) values (40, 'VP Quality Control', 7);
insert into canvases (id, title, owner_id) values (41, 'Marketing Manager', 45);
insert into canvases (id, title, owner_id) values (42, 'Senior Financial Analyst', 89);
insert into canvases (id, title, owner_id) values (43, 'Web Developer III', 90);
insert into canvases (id, title, owner_id) values (44, 'Internal Auditor', 41);
insert into canvases (id, title, owner_id) values (45, 'Financial Analyst', 98);
insert into canvases (id, title, owner_id) values (46, 'Technical Writer', 87);
insert into canvases (id, title, owner_id) values (47, 'Nurse Practicioner', 34);
insert into canvases (id, title, owner_id) values (48, 'Electrical Engineer', 89);
insert into canvases (id, title, owner_id) values (49, 'VP Marketing', 37);
insert into canvases (id, title, owner_id) values (50, 'VP Accounting', 54);
insert into canvases (id, title, owner_id) values (51, 'Engineer III', 33);
insert into canvases (id, title, owner_id) values (52, 'Database Administrator IV', 10);
insert into canvases (id, title, owner_id) values (53, 'Food Chemist', 14);
insert into canvases (id, title, owner_id) values (54, 'Desktop Support Technician', 82);
insert into canvases (id, title, owner_id) values (55, 'Senior Editor', 5);
insert into canvases (id, title, owner_id) values (56, 'Account Representative II', 24);
insert into canvases (id, title, owner_id) values (57, 'Dental Hygienist', 44);
insert into canvases (id, title, owner_id) values (58, 'Nurse Practicioner', 53);
insert into canvases (id, title, owner_id) values (59, 'GIS Technical Architect', 77);
insert into canvases (id, title, owner_id) values (60, 'Software Test Engineer II', 37);
insert into canvases (id, title, owner_id) values (61, 'Librarian', 19);
insert into canvases (id, title, owner_id) values (62, 'Senior Cost Accountant', 54);
insert into canvases (id, title, owner_id) values (63, 'Budget/Accounting Analyst IV', 85);
insert into canvases (id, title, owner_id) values (64, 'Senior Financial Analyst', 41);
insert into canvases (id, title, owner_id) values (65, 'GIS Technical Architect', 38);
insert into canvases (id, title, owner_id) values (66, 'Recruiting Manager', 3);
insert into canvases (id, title, owner_id) values (67, 'Senior Quality Engineer', 17);
insert into canvases (id, title, owner_id) values (68, 'Executive Secretary', 51);
insert into canvases (id, title, owner_id) values (69, 'Payment Adjustment Coordinator', 27);
insert into canvases (id, title, owner_id) values (70, 'Junior Executive', 56);
insert into canvases (id, title, owner_id) values (71, 'Senior Financial Analyst', 78);
insert into canvases (id, title, owner_id) values (72, 'Account Representative III', 80);
insert into canvases (id, title, owner_id) values (73, 'Financial Advisor', 53);
insert into canvases (id, title, owner_id) values (74, 'Actuary', 60);
insert into canvases (id, title, owner_id) values (75, 'Executive Secretary', 33);
insert into canvases (id, title, owner_id) values (76, 'Human Resources Assistant II', 54);
insert into canvases (id, title, owner_id) values (77, 'Chief Design Engineer', 93);
insert into canvases (id, title, owner_id) values (78, 'Registered Nurse', 37);
insert into canvases (id, title, owner_id) values (79, 'Operator', 90);
insert into canvases (id, title, owner_id) values (80, 'Statistician IV', 80);
insert into canvases (id, title, owner_id) values (81, 'Staff Accountant I', 99);
insert into canvases (id, title, owner_id) values (82, 'Biostatistician II', 1);
insert into canvases (id, title, owner_id) values (83, 'Office Assistant I', 24);
insert into canvases (id, title, owner_id) values (84, 'Assistant Manager', 45);
insert into canvases (id, title, owner_id) values (85, 'Executive Secretary', 16);
insert into canvases (id, title, owner_id) values (86, 'Computer Systems Analyst III', 82);
insert into canvases (id, title, owner_id) values (87, 'Clinical Specialist', 45);
insert into canvases (id, title, owner_id) values (88, 'Executive Secretary', 55);
insert into canvases (id, title, owner_id) values (89, 'Account Coordinator', 2);
insert into canvases (id, title, owner_id) values (90, 'Actuary', 82);
insert into canvases (id, title, owner_id) values (91, 'Staff Accountant III', 68);
insert into canvases (id, title, owner_id) values (92, 'General Manager', 63);
insert into canvases (id, title, owner_id) values (93, 'Chemical Engineer', 67);
insert into canvases (id, title, owner_id) values (94, 'Speech Pathologist', 22);
insert into canvases (id, title, owner_id) values (95, 'Librarian', 33);
insert into canvases (id, title, owner_id) values (96, 'Web Developer II', 30);
insert into canvases (id, title, owner_id) values (97, 'Nuclear Power Engineer', 80);
insert into canvases (id, title, owner_id) values (98, 'Information Systems Manager', 21);
insert into canvases (id, title, owner_id) values (99, 'Programmer II', 77);
insert into canvases (id, title, owner_id) values (100, 'Software Engineer III', 78);
