CREATE USER u1 WITH LOGIN PASSWORD 'password_1';
CREATE USER u2 WITH LOGIN PASSWORD 'password_1';

CREATE TABLE IF NOT EXISTS sample_table ();

GRANT ALL PRIVILEGES ON TABLE sample_table TO u1;
GRANT SELECT, INSERT, UPDATE ON TABLE sample_table TO u2;
